language: php
dist: bionic
php:
    - '8.1.0'
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php:
              - nightly

before_script:
    - composer install
    - vendor/bin/phpstan analyse -l 9 src tests
